[package]
name = "bevy_replicon_snap"
version = "0.1.0"
edition = "2021"
#keywords = "networking, netcode, bevy, bevy_replicon, snapshot, interpolation, prediction"
description = "High-level networking crate that extends the bevy_replicon crate to allow snapshot interpolation and client-side prediction"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", default_features = false }
bevy_replicon = "0.14.0"
serde = "1.0"

bevy_replicon_snap_macros = { path = "macros" }